CXX = g++

CXXFLAGS = -std=c++0x

CXXFLAGS += -Wall


CXXFLAGS += -pedantic-errors

CXXFLAGS += -g




# SRCS are the source files
SRCS = debug.cpp

OBJS = debug.o
# HEADERS is the header files 

HEADER1 = 
HEADER2 = 
HEADERS = 

#  executables
PROG1 = lecture
PROGS = ${PROG1}


#make all
all:
	${CXX} ${CXXFLAGS} ${SRCS} -o ${PROG1}


#make clean, to clean out the executables
clean: 
	rm -f ${PROGS} *.o *~
