CXX = g++

CXXFLAGS = -std=c++0x



# SRCS are the source files
SRC1 = main.cpp
SRCS = ${SRC1}

#  executables
PROG1 = main
PROGS = ${PROG1}


#make all
all:
	${CXX} ${CXXFLAGS} ${SRCS} -o ${PROG1}
    #


#make clean, to clean out the executables
clean: 
	rm -f ${PROGS} *.o *~