CXX = g++

CXXFLAGS = -std=c++0x



SRC1 = main.cpp
SRC2 = utilities.cpp

SRCS = ${SRC1} ${SRC2} 



# executables
PROG1 = lab
PROGS = ${PROG1}
#make all
all:
		${CXX} ${CXXFLAGS} ${SRCS} -o ${PROG1}


#make clean, to clean out the executables
clean: 
		rm -f ${PROGS} *.o *~