langAnt: main.cpp langAnt.cpp langBoard.cpp utilityFile.cpp langBoard.h langAnt.h utilityFile.h
	
		g++ -std=c++0x main.cpp langAnt.cpp langBoard.cpp utilityFile.cpp -o lang


clean:
     \rm *.o *~ p1